apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: validation-webhook
spec:
  scopes:
    - Namespaced
  phases:
    - name: webhooks
      class: hosted-cluster
    - name: rbac
    - name: config
    - name: deploy
  availabilityProbes:
    - probes:
        - condition:
            type: Available
            status: "True"
        - fieldsEqual:
            fieldA: .status.updatedReplicas
            fieldB: .status.replicas
      selector:
        kind:
          group: apps
          kind: Deployment
