apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: validation-webhook
spec:
  scopes:
    - Namespaced
  phases:
    - name: config
    - name: rbac
    - name: deploy
    - name: webhooks
      class: hosted-cluster
  config:
    openAPIV3Schema:
      properties:
        serviceca:
          description: Service Certificate Authority used for webhook client authentication
          type: string
      required:
      - serviceca
      type: object
  availabilityProbes:
    - probes:
        - condition:
            type: Available
            status: "True"
        - fieldsEqual:
            fieldA: .status.updatedReplicas
            fieldB: .status.replicas
      selector:
        kind:
          group: apps
          kind: Deployment
